(function () {
  'use strict';

  const dictionaries = {
    de: {
      'IDLE':'BEREIT','ACTIVE':'AKTIV','INACTIVE':'INAKTIV','START REFRESH':'AKTUALISIERUNG STARTEN','STOP REFRESH':'AKTUALISIERUNG STOPPEN','Timer':'Timer','Monitor':'Überwachung','Auto-Start':'Auto-Start','Preset Intervals':'Vorgegebene Intervalle','Custom Duration':'Eigene Dauer','Hrs':'Std.','Min':'Min.','Sec':'Sek.','Random Interval Range':'Zufälliger Intervallbereich','Bypass anti-bot rate limits':'Gleichmäßige Abrufmuster vermeiden','Min (sec):':'Min. (Sek.):','Max (sec):':'Max. (Sek.):','Refresh Limit Count (0 = Unlimited):':'Aktualisierungslimit (0 = unbegrenzt):','Hard Refresh':'Vollständige Aktualisierung','Bypass browser cache':'Browser-Cache umgehen','On-Page Overlay Widget':'Widget auf der Webseite','Show draggable timer on page':'Verschiebbaren Timer anzeigen','Stop on Touch / Interaction':'Bei Berührung / Interaktion stoppen','Stop refresh if you tap or type on page':'Beim Tippen oder Berühren der Seite stoppen','Auto-Start Exact Page':'Auto-Start für genaue Seite','Automatically start auto-refreshing only when you visit this exact page URL.':'Automatische Aktualisierung nur bei genau dieser Seiten-URL starten.','+ Auto-Start Current Page':'+ Aktuelle Seite automatisch starten','Manage Rules in Extension →':'Regeln in der Erweiterung verwalten →','Auto-Start Rules':'Auto-Start-Regeln','Edit exact page URLs and their starting intervals.':'Genaue Seiten-URLs und Startintervalle bearbeiten.','Edit Auto-Start Rule':'Auto-Start-Regel bearbeiten','Page URL':'Seiten-URL','Default interval (seconds)':'Standardintervall (Sekunden)','Save Changes':'Änderungen speichern','Cancel':'Abbrechen','Enable Content Monitoring':'Inhaltsüberwachung aktivieren','Scan page for text/regex changes':'Seite auf Text- oder Regex-Änderungen prüfen','Target Text or Expression':'Zieltext oder Ausdruck','e.g. In Stock, Out of Stock, Available...':'z. B. Auf Lager, Nicht auf Lager, Verfügbar …','Match Mode':'Vergleichsmodus','Plain Text':'Einfacher Text','Regular Expression':'Regulärer Ausdruck','XPath Selector':'XPath-Selektor','Condition':'Bedingung','Target Appears':'Ziel erscheint','Target Disappears':'Ziel verschwindet','Actions When Detected':'Aktionen bei Erkennung','Stop Refresh':'Aktualisierung stoppen','Sound Alert':'Akustischer Alarm','Highlight Element':'Element hervorheben','Auto-Scroll to Element':'Automatisch zum Element scrollen','🔊 Test Notification Sound':'🔊 Benachrichtigungston testen','Delete Auto-Start rule?':'Auto-Start-Regel löschen?','This will permanently remove Auto-Start for:':'Dadurch wird Auto-Start dauerhaft entfernt für:','Delete Rule':'Regel löschen','Advanced Auto-Start rule editor':'Erweiterter Editor für Auto-Start-Regeln','No auto-start rules created yet.':'Noch keine Auto-Start-Regeln erstellt.','Edit Rule':'Regel bearbeiten','Exact page URL':'Genaue Seiten-URL'
    },
    fr: {
      'IDLE':'INACTIF','ACTIVE':'ACTIF','INACTIVE':'INACTIF','START REFRESH':'DÉMARRER','STOP REFRESH':'ARRÊTER','Timer':'Minuteur','Monitor':'Surveillance','Auto-Start':'Démarrage auto','Preset Intervals':'Intervalles prédéfinis','Custom Duration':'Durée personnalisée','Hrs':'h','Min':'min','Sec':'s','Random Interval Range':'Plage d’intervalle aléatoire','Bypass anti-bot rate limits':'Éviter les schémas de requêtes réguliers','Min (sec):':'Min (s) :','Max (sec):':'Max (s) :','Refresh Limit Count (0 = Unlimited):':'Limite d’actualisations (0 = illimité) :','Hard Refresh':'Actualisation forcée','Bypass browser cache':'Ignorer le cache du navigateur','On-Page Overlay Widget':'Widget superposé sur la page','Show draggable timer on page':'Afficher un minuteur déplaçable','Stop on Touch / Interaction':'Arrêter lors d’une interaction','Stop refresh if you tap or type on page':'Arrêter si vous touchez la page ou saisissez du texte','Auto-Start Exact Page':'Démarrage auto de cette page','Automatically start auto-refreshing only when you visit this exact page URL.':'Démarrer l’actualisation automatique uniquement pour cette URL exacte.','+ Auto-Start Current Page':'+ Démarrer automatiquement cette page','Manage Rules in Extension →':'Gérer les règles dans l’extension →','Auto-Start Rules':'Règles de démarrage auto','Edit exact page URLs and their starting intervals.':'Modifier les URL exactes et leurs intervalles de départ.','Edit Auto-Start Rule':'Modifier la règle','Page URL':'URL de la page','Default interval (seconds)':'Intervalle par défaut (secondes)','Save Changes':'Enregistrer','Cancel':'Annuler','Enable Content Monitoring':'Activer la surveillance du contenu','Scan page for text/regex changes':'Rechercher les changements de texte ou d’expression','Target Text or Expression':'Texte ou expression cible','e.g. In Stock, Out of Stock, Available...':'ex. En stock, Épuisé, Disponible…','Match Mode':'Mode de correspondance','Plain Text':'Texte simple','Regular Expression':'Expression régulière','XPath Selector':'Sélecteur XPath','Condition':'Condition','Target Appears':'La cible apparaît','Target Disappears':'La cible disparaît','Actions When Detected':'Actions lors de la détection','Stop Refresh':'Arrêter l’actualisation','Sound Alert':'Alerte sonore','Highlight Element':'Surligner l’élément','Auto-Scroll to Element':'Faire défiler jusqu’à l’élément','🔊 Test Notification Sound':'🔊 Tester le son de notification','Delete Auto-Start rule?':'Supprimer la règle de démarrage auto ?','This will permanently remove Auto-Start for:':'Le démarrage auto sera définitivement supprimé pour :','Delete Rule':'Supprimer la règle','Advanced Auto-Start rule editor':'Éditeur avancé des règles de démarrage auto','No auto-start rules created yet.':'Aucune règle de démarrage auto.','Edit Rule':'Modifier la règle','Exact page URL':'URL exacte de la page'
    },
    es: {
      'IDLE':'INACTIVO','ACTIVE':'ACTIVO','INACTIVE':'INACTIVO','START REFRESH':'INICIAR RECARGA','STOP REFRESH':'DETENER RECARGA','Timer':'Temporizador','Monitor':'Monitor','Auto-Start':'Inicio automático','Preset Intervals':'Intervalos predefinidos','Custom Duration':'Duración personalizada','Hrs':'h','Min':'min','Sec':'s','Random Interval Range':'Intervalo aleatorio','Bypass anti-bot rate limits':'Evitar patrones regulares de solicitudes','Min (sec):':'Mín. (s):','Max (sec):':'Máx. (s):','Refresh Limit Count (0 = Unlimited):':'Límite de recargas (0 = ilimitado):','Hard Refresh':'Recarga completa','Bypass browser cache':'Omitir la caché del navegador','On-Page Overlay Widget':'Widget superpuesto','Show draggable timer on page':'Mostrar temporizador arrastrable','Stop on Touch / Interaction':'Detener al interactuar','Stop refresh if you tap or type on page':'Detener al tocar o escribir en la página','Auto-Start Exact Page':'Inicio automático de esta página','Automatically start auto-refreshing only when you visit this exact page URL.':'Iniciar la recarga automática solo al visitar esta URL exacta.','+ Auto-Start Current Page':'+ Iniciar automáticamente esta página','Manage Rules in Extension →':'Gestionar reglas en la extensión →','Auto-Start Rules':'Reglas de inicio automático','Edit exact page URLs and their starting intervals.':'Edita las URL exactas y sus intervalos iniciales.','Edit Auto-Start Rule':'Editar regla de inicio automático','Page URL':'URL de la página','Default interval (seconds)':'Intervalo predeterminado (segundos)','Save Changes':'Guardar cambios','Cancel':'Cancelar','Enable Content Monitoring':'Activar monitorización de contenido','Scan page for text/regex changes':'Buscar cambios de texto o expresiones','Target Text or Expression':'Texto o expresión objetivo','e.g. In Stock, Out of Stock, Available...':'p. ej., En stock, Agotado, Disponible…','Match Mode':'Modo de coincidencia','Plain Text':'Texto sin formato','Regular Expression':'Expresión regular','XPath Selector':'Selector XPath','Condition':'Condición','Target Appears':'El objetivo aparece','Target Disappears':'El objetivo desaparece','Actions When Detected':'Acciones al detectar','Stop Refresh':'Detener recarga','Sound Alert':'Alerta sonora','Highlight Element':'Resaltar elemento','Auto-Scroll to Element':'Desplazar hasta el elemento','🔊 Test Notification Sound':'🔊 Probar sonido de notificación','Delete Auto-Start rule?':'¿Eliminar la regla de inicio automático?','This will permanently remove Auto-Start for:':'Se eliminará permanentemente el inicio automático de:','Delete Rule':'Eliminar regla','Advanced Auto-Start rule editor':'Editor avanzado de reglas de inicio automático','No auto-start rules created yet.':'Aún no hay reglas de inicio automático.','Edit Rule':'Editar regla','Exact page URL':'URL exacta de la página'
    },
    it: {
      'IDLE':'INATTIVO','ACTIVE':'ATTIVO','INACTIVE':'INATTIVO','START REFRESH':'AVVIA AGGIORNAMENTO','STOP REFRESH':'INTERROMPI','Timer':'Timer','Monitor':'Monitor','Auto-Start':'Avvio automatico','Preset Intervals':'Intervalli predefiniti','Custom Duration':'Durata personalizzata','Hrs':'ore','Min':'min','Sec':'sec','Random Interval Range':'Intervallo casuale','Bypass anti-bot rate limits':'Evita schemi regolari di richieste','Min (sec):':'Min (sec):','Max (sec):':'Max (sec):','Refresh Limit Count (0 = Unlimited):':'Limite aggiornamenti (0 = illimitato):','Hard Refresh':'Aggiornamento completo','Bypass browser cache':'Ignora la cache del browser','On-Page Overlay Widget':'Widget sovrapposto alla pagina','Show draggable timer on page':'Mostra timer trascinabile','Stop on Touch / Interaction':'Interrompi all’interazione','Stop refresh if you tap or type on page':'Interrompi se tocchi o scrivi nella pagina','Auto-Start Exact Page':'Avvio automatico pagina esatta','Automatically start auto-refreshing only when you visit this exact page URL.':'Avvia l’aggiornamento automatico solo per questo URL esatto.','+ Auto-Start Current Page':'+ Avvio automatico pagina corrente','Manage Rules in Extension →':'Gestisci regole nell’estensione →','Auto-Start Rules':'Regole di avvio automatico','Edit exact page URLs and their starting intervals.':'Modifica URL esatti e intervalli iniziali.','Edit Auto-Start Rule':'Modifica regola','Page URL':'URL pagina','Default interval (seconds)':'Intervallo predefinito (secondi)','Save Changes':'Salva modifiche','Cancel':'Annulla','Enable Content Monitoring':'Attiva monitoraggio contenuti','Scan page for text/regex changes':'Cerca modifiche di testo o regex','Target Text or Expression':'Testo o espressione da cercare','e.g. In Stock, Out of Stock, Available...':'es. Disponibile, Esaurito…','Match Mode':'Modalità di corrispondenza','Plain Text':'Testo semplice','Regular Expression':'Espressione regolare','XPath Selector':'Selettore XPath','Condition':'Condizione','Target Appears':'Il target appare','Target Disappears':'Il target scompare','Actions When Detected':'Azioni al rilevamento','Stop Refresh':'Interrompi aggiornamento','Sound Alert':'Avviso sonoro','Highlight Element':'Evidenzia elemento','Auto-Scroll to Element':'Scorri fino all’elemento','🔊 Test Notification Sound':'🔊 Prova suono notifica','Delete Auto-Start rule?':'Eliminare la regola di avvio automatico?','This will permanently remove Auto-Start for:':'L’avvio automatico verrà rimosso definitivamente per:','Delete Rule':'Elimina regola','Advanced Auto-Start rule editor':'Editor avanzato delle regole','No auto-start rules created yet.':'Nessuna regola di avvio automatico.','Edit Rule':'Modifica regola','Exact page URL':'URL esatto della pagina'
    },
    pt: {
      'IDLE':'INATIVO','ACTIVE':'ATIVO','INACTIVE':'INATIVO','START REFRESH':'INICIAR ATUALIZAÇÃO','STOP REFRESH':'PARAR ATUALIZAÇÃO','Timer':'Temporizador','Monitor':'Monitorização','Auto-Start':'Início automático','Preset Intervals':'Intervalos predefinidos','Custom Duration':'Duração personalizada','Hrs':'h','Min':'min','Sec':'s','Random Interval Range':'Intervalo aleatório','Bypass anti-bot rate limits':'Evitar padrões regulares de pedidos','Min (sec):':'Mín. (s):','Max (sec):':'Máx. (s):','Refresh Limit Count (0 = Unlimited):':'Limite de atualizações (0 = ilimitado):','Hard Refresh':'Atualização completa','Bypass browser cache':'Ignorar a cache do navegador','On-Page Overlay Widget':'Widget sobre a página','Show draggable timer on page':'Mostrar temporizador arrastável','Stop on Touch / Interaction':'Parar ao interagir','Stop refresh if you tap or type on page':'Parar ao tocar ou escrever na página','Auto-Start Exact Page':'Início automático desta página','Automatically start auto-refreshing only when you visit this exact page URL.':'Iniciar a atualização automática apenas neste URL exato.','+ Auto-Start Current Page':'+ Iniciar automaticamente esta página','Manage Rules in Extension →':'Gerir regras na extensão →','Auto-Start Rules':'Regras de início automático','Edit exact page URLs and their starting intervals.':'Edite URLs exatos e os intervalos iniciais.','Edit Auto-Start Rule':'Editar regra','Page URL':'URL da página','Default interval (seconds)':'Intervalo predefinido (segundos)','Save Changes':'Guardar alterações','Cancel':'Cancelar','Enable Content Monitoring':'Ativar monitorização de conteúdo','Scan page for text/regex changes':'Procurar alterações de texto ou regex','Target Text or Expression':'Texto ou expressão alvo','e.g. In Stock, Out of Stock, Available...':'ex.: Em stock, Esgotado, Disponível…','Match Mode':'Modo de correspondência','Plain Text':'Texto simples','Regular Expression':'Expressão regular','XPath Selector':'Seletor XPath','Condition':'Condição','Target Appears':'O alvo aparece','Target Disappears':'O alvo desaparece','Actions When Detected':'Ações ao detetar','Stop Refresh':'Parar atualização','Sound Alert':'Alerta sonoro','Highlight Element':'Realçar elemento','Auto-Scroll to Element':'Deslocar até ao elemento','🔊 Test Notification Sound':'🔊 Testar som de notificação','Delete Auto-Start rule?':'Eliminar regra de início automático?','This will permanently remove Auto-Start for:':'O início automático será removido permanentemente para:','Delete Rule':'Eliminar regra','Advanced Auto-Start rule editor':'Editor avançado de regras','No auto-start rules created yet.':'Ainda não existem regras de início automático.','Edit Rule':'Editar regra','Exact page URL':'URL exato da página'
    },
    nl: {
      'IDLE':'INACTIEF','ACTIVE':'ACTIEF','INACTIVE':'INACTIEF','START REFRESH':'VERVERSEN STARTEN','STOP REFRESH':'VERVERSEN STOPPEN','Timer':'Timer','Monitor':'Controle','Auto-Start':'Automatisch starten','Preset Intervals':'Vooraf ingestelde intervallen','Custom Duration':'Aangepaste duur','Hrs':'uur','Min':'min','Sec':'sec','Random Interval Range':'Willekeurig interval','Bypass anti-bot rate limits':'Vaste aanvraagpatronen vermijden','Min (sec):':'Min. (sec):','Max (sec):':'Max. (sec):','Refresh Limit Count (0 = Unlimited):':'Verversingslimiet (0 = onbeperkt):','Hard Refresh':'Volledig verversen','Bypass browser cache':'Browsercache omzeilen','On-Page Overlay Widget':'Widget op de pagina','Show draggable timer on page':'Versleepbare timer tonen','Stop on Touch / Interaction':'Stoppen bij interactie','Stop refresh if you tap or type on page':'Stoppen bij tikken of typen op de pagina','Auto-Start Exact Page':'Deze pagina automatisch starten','Automatically start auto-refreshing only when you visit this exact page URL.':'Automatisch verversen alleen starten bij deze exacte URL.','+ Auto-Start Current Page':'+ Huidige pagina automatisch starten','Manage Rules in Extension →':'Regels in extensie beheren →','Auto-Start Rules':'Regels voor automatisch starten','Edit exact page URLs and their starting intervals.':'Bewerk exacte URL’s en startintervallen.','Edit Auto-Start Rule':'Regel bewerken','Page URL':'Pagina-URL','Default interval (seconds)':'Standaardinterval (seconden)','Save Changes':'Wijzigingen opslaan','Cancel':'Annuleren','Enable Content Monitoring':'Inhoud controleren','Scan page for text/regex changes':'Pagina controleren op tekst- of regexwijzigingen','Target Text or Expression':'Doeltekst of expressie','e.g. In Stock, Out of Stock, Available...':'bijv. Op voorraad, Uitverkocht, Beschikbaar…','Match Mode':'Overeenkomstmodus','Plain Text':'Platte tekst','Regular Expression':'Reguliere expressie','XPath Selector':'XPath-selector','Condition':'Voorwaarde','Target Appears':'Doel verschijnt','Target Disappears':'Doel verdwijnt','Actions When Detected':'Acties bij detectie','Stop Refresh':'Verversen stoppen','Sound Alert':'Geluidsmelding','Highlight Element':'Element markeren','Auto-Scroll to Element':'Automatisch naar element scrollen','🔊 Test Notification Sound':'🔊 Meldingsgeluid testen','Delete Auto-Start rule?':'Regel voor automatisch starten verwijderen?','This will permanently remove Auto-Start for:':'Automatisch starten wordt permanent verwijderd voor:','Delete Rule':'Regel verwijderen','Advanced Auto-Start rule editor':'Geavanceerde regeleditor','No auto-start rules created yet.':'Nog geen regels gemaakt.','Edit Rule':'Regel bewerken','Exact page URL':'Exacte pagina-URL'
    },
    ja: {
      'IDLE':'待機中','ACTIVE':'実行中','INACTIVE':'停止中','START REFRESH':'更新を開始','STOP REFRESH':'更新を停止','Timer':'タイマー','Monitor':'監視','Auto-Start':'自動開始','Preset Intervals':'プリセット間隔','Custom Duration':'カスタム時間','Hrs':'時間','Min':'分','Sec':'秒','Random Interval Range':'ランダム間隔','Bypass anti-bot rate limits':'一定のリクエストパターンを回避','Min (sec):':'最小（秒）:','Max (sec):':'最大（秒）:','Refresh Limit Count (0 = Unlimited):':'更新回数の上限（0 = 無制限）:','Hard Refresh':'完全更新','Bypass browser cache':'ブラウザキャッシュを使用しない','On-Page Overlay Widget':'ページ上のウィジェット','Show draggable timer on page':'移動できるタイマーを表示','Stop on Touch / Interaction':'操作時に停止','Stop refresh if you tap or type on page':'ページをタップまたは入力したら停止','Auto-Start Exact Page':'このページを自動開始','Automatically start auto-refreshing only when you visit this exact page URL.':'この正確なURLを開いたときだけ自動更新を開始します。','+ Auto-Start Current Page':'+ 現在のページを自動開始','Manage Rules in Extension →':'拡張機能でルールを管理 →','Auto-Start Rules':'自動開始ルール','Edit exact page URLs and their starting intervals.':'正確なページURLと開始間隔を編集します。','Edit Auto-Start Rule':'自動開始ルールを編集','Page URL':'ページURL','Default interval (seconds)':'既定の間隔（秒）','Save Changes':'変更を保存','Cancel':'キャンセル','Enable Content Monitoring':'コンテンツ監視を有効にする','Scan page for text/regex changes':'テキストまたは正規表現の変化を確認','Target Text or Expression':'対象テキストまたは式','e.g. In Stock, Out of Stock, Available...':'例：在庫あり、在庫切れ、利用可能…','Match Mode':'一致モード','Plain Text':'プレーンテキスト','Regular Expression':'正規表現','XPath Selector':'XPathセレクター','Condition':'条件','Target Appears':'対象が表示されたとき','Target Disappears':'対象が消えたとき','Actions When Detected':'検出時の動作','Stop Refresh':'更新を停止','Sound Alert':'サウンド通知','Highlight Element':'要素を強調表示','Auto-Scroll to Element':'要素まで自動スクロール','🔊 Test Notification Sound':'🔊 通知音をテスト','Delete Auto-Start rule?':'自動開始ルールを削除しますか？','This will permanently remove Auto-Start for:':'次の自動開始設定を完全に削除します：','Delete Rule':'ルールを削除','Advanced Auto-Start rule editor':'高度な自動開始ルール編集','No auto-start rules created yet.':'自動開始ルールはまだありません。','Edit Rule':'ルールを編集','Exact page URL':'正確なページURL'
    },
    ko: {
      'IDLE':'대기','ACTIVE':'실행 중','INACTIVE':'중지됨','START REFRESH':'새로고침 시작','STOP REFRESH':'새로고침 중지','Timer':'타이머','Monitor':'모니터','Auto-Start':'자동 시작','Preset Intervals':'사전 설정 간격','Custom Duration':'사용자 지정 시간','Hrs':'시간','Min':'분','Sec':'초','Random Interval Range':'무작위 간격 범위','Bypass anti-bot rate limits':'일정한 요청 패턴 방지','Min (sec):':'최소(초):','Max (sec):':'최대(초):','Refresh Limit Count (0 = Unlimited):':'새로고침 제한(0 = 무제한):','Hard Refresh':'강력 새로고침','Bypass browser cache':'브라우저 캐시 우회','On-Page Overlay Widget':'페이지 오버레이 위젯','Show draggable timer on page':'드래그 가능한 타이머 표시','Stop on Touch / Interaction':'상호 작용 시 중지','Stop refresh if you tap or type on page':'페이지를 탭하거나 입력하면 중지','Auto-Start Exact Page':'정확한 페이지 자동 시작','Automatically start auto-refreshing only when you visit this exact page URL.':'이 정확한 URL을 방문할 때만 자동 새로고침을 시작합니다.','+ Auto-Start Current Page':'+ 현재 페이지 자동 시작','Manage Rules in Extension →':'확장 프로그램에서 규칙 관리 →','Auto-Start Rules':'자동 시작 규칙','Edit exact page URLs and their starting intervals.':'정확한 페이지 URL과 시작 간격을 편집합니다.','Edit Auto-Start Rule':'자동 시작 규칙 편집','Page URL':'페이지 URL','Default interval (seconds)':'기본 간격(초)','Save Changes':'변경 사항 저장','Cancel':'취소','Enable Content Monitoring':'콘텐츠 모니터링 사용','Scan page for text/regex changes':'텍스트 또는 정규식 변경 감지','Target Text or Expression':'대상 텍스트 또는 식','e.g. In Stock, Out of Stock, Available...':'예: 재고 있음, 품절, 사용 가능…','Match Mode':'일치 모드','Plain Text':'일반 텍스트','Regular Expression':'정규식','XPath Selector':'XPath 선택자','Condition':'조건','Target Appears':'대상이 나타남','Target Disappears':'대상이 사라짐','Actions When Detected':'감지 시 동작','Stop Refresh':'새로고침 중지','Sound Alert':'소리 알림','Highlight Element':'요소 강조','Auto-Scroll to Element':'요소로 자동 스크롤','🔊 Test Notification Sound':'🔊 알림음 테스트','Delete Auto-Start rule?':'자동 시작 규칙을 삭제할까요?','This will permanently remove Auto-Start for:':'다음 페이지의 자동 시작이 영구적으로 삭제됩니다:','Delete Rule':'규칙 삭제','Advanced Auto-Start rule editor':'고급 자동 시작 규칙 편집기','No auto-start rules created yet.':'아직 자동 시작 규칙이 없습니다.','Edit Rule':'규칙 편집','Exact page URL':'정확한 페이지 URL'
    },
    'zh-CN': {
      'IDLE':'空闲','ACTIVE':'运行中','INACTIVE':'已停止','START REFRESH':'开始刷新','STOP REFRESH':'停止刷新','Timer':'计时器','Monitor':'监控','Auto-Start':'自动启动','Preset Intervals':'预设间隔','Custom Duration':'自定义时长','Hrs':'小时','Min':'分钟','Sec':'秒','Random Interval Range':'随机间隔范围','Bypass anti-bot rate limits':'避免固定请求模式','Min (sec):':'最短（秒）：','Max (sec):':'最长（秒）：','Refresh Limit Count (0 = Unlimited):':'刷新次数上限（0 = 不限）：','Hard Refresh':'强制刷新','Bypass browser cache':'绕过浏览器缓存','On-Page Overlay Widget':'页面悬浮组件','Show draggable timer on page':'在页面上显示可拖动计时器','Stop on Touch / Interaction':'交互时停止','Stop refresh if you tap or type on page':'点击或输入时停止刷新','Auto-Start Exact Page':'自动启动当前页面','Automatically start auto-refreshing only when you visit this exact page URL.':'仅在访问此确切网址时自动开始刷新。','+ Auto-Start Current Page':'+ 自动启动当前页面','Manage Rules in Extension →':'在扩展中管理规则 →','Auto-Start Rules':'自动启动规则','Edit exact page URLs and their starting intervals.':'编辑确切页面网址及其启动间隔。','Edit Auto-Start Rule':'编辑自动启动规则','Page URL':'页面网址','Default interval (seconds)':'默认间隔（秒）','Save Changes':'保存更改','Cancel':'取消','Enable Content Monitoring':'启用内容监控','Scan page for text/regex changes':'扫描文本或正则表达式变化','Target Text or Expression':'目标文本或表达式','e.g. In Stock, Out of Stock, Available...':'例如：有货、缺货、可用…','Match Mode':'匹配模式','Plain Text':'纯文本','Regular Expression':'正则表达式','XPath Selector':'XPath 选择器','Condition':'条件','Target Appears':'目标出现','Target Disappears':'目标消失','Actions When Detected':'检测到时执行','Stop Refresh':'停止刷新','Sound Alert':'声音提醒','Highlight Element':'高亮元素','Auto-Scroll to Element':'自动滚动到元素','🔊 Test Notification Sound':'🔊 测试通知声音','Delete Auto-Start rule?':'删除自动启动规则？','This will permanently remove Auto-Start for:':'这将永久移除以下页面的自动启动：','Delete Rule':'删除规则','Advanced Auto-Start rule editor':'高级自动启动规则编辑器','No auto-start rules created yet.':'尚未创建自动启动规则。','Edit Rule':'编辑规则','Exact page URL':'确切页面网址'
    },
    'zh-TW': {
      'IDLE':'閒置','ACTIVE':'執行中','INACTIVE':'已停止','START REFRESH':'開始重新整理','STOP REFRESH':'停止重新整理','Timer':'計時器','Monitor':'監控','Auto-Start':'自動啟動','Preset Intervals':'預設間隔','Custom Duration':'自訂時間','Hrs':'小時','Min':'分鐘','Sec':'秒','Random Interval Range':'隨機間隔範圍','Bypass anti-bot rate limits':'避免固定的請求模式','Min (sec):':'最短（秒）：','Max (sec):':'最長（秒）：','Refresh Limit Count (0 = Unlimited):':'重新整理次數上限（0 = 不限）：','Hard Refresh':'強制重新整理','Bypass browser cache':'略過瀏覽器快取','On-Page Overlay Widget':'頁面浮動小工具','Show draggable timer on page':'顯示可拖曳的計時器','Stop on Touch / Interaction':'互動時停止','Stop refresh if you tap or type on page':'點按或輸入時停止重新整理','Auto-Start Exact Page':'自動啟動目前頁面','Automatically start auto-refreshing only when you visit this exact page URL.':'只有造訪此確切網址時才自動開始重新整理。','+ Auto-Start Current Page':'+ 自動啟動目前頁面','Manage Rules in Extension →':'在擴充功能中管理規則 →','Auto-Start Rules':'自動啟動規則','Edit exact page URLs and their starting intervals.':'編輯確切頁面網址及其啟動間隔。','Edit Auto-Start Rule':'編輯自動啟動規則','Page URL':'頁面網址','Default interval (seconds)':'預設間隔（秒）','Save Changes':'儲存變更','Cancel':'取消','Enable Content Monitoring':'啟用內容監控','Scan page for text/regex changes':'掃描文字或規則運算式變化','Target Text or Expression':'目標文字或運算式','e.g. In Stock, Out of Stock, Available...':'例如：有貨、缺貨、可用…','Match Mode':'比對模式','Plain Text':'純文字','Regular Expression':'規則運算式','XPath Selector':'XPath 選擇器','Condition':'條件','Target Appears':'目標出現','Target Disappears':'目標消失','Actions When Detected':'偵測到時執行','Stop Refresh':'停止重新整理','Sound Alert':'聲音提醒','Highlight Element':'醒目提示元素','Auto-Scroll to Element':'自動捲動到元素','🔊 Test Notification Sound':'🔊 測試通知聲音','Delete Auto-Start rule?':'刪除自動啟動規則？','This will permanently remove Auto-Start for:':'這會永久移除以下頁面的自動啟動：','Delete Rule':'刪除規則','Advanced Auto-Start rule editor':'進階自動啟動規則編輯器','No auto-start rules created yet.':'尚未建立自動啟動規則。','Edit Rule':'編輯規則','Exact page URL':'確切頁面網址'
    }
  };

  const rawLanguage = (navigator.language || 'en').replace('_', '-');
  const language = dictionaries[rawLanguage] ? rawLanguage : (dictionaries[rawLanguage.split('-')[0]] ? rawLanguage.split('-')[0] : 'en');
  const dictionary = dictionaries[language] || {};
  const t = (source, replacements = []) => {
    let value = dictionary[source] || source;
    replacements.forEach((replacement, index) => { value = value.replace(new RegExp(`\\$${index + 1}`, 'g'), replacement); });
    return value;
  };

  function localizeDocument(root = document) {
    document.documentElement.lang = rawLanguage;
    const walker = document.createTreeWalker(root.body || root, NodeFilter.SHOW_TEXT);
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    for (const node of nodes) {
      if (node.parentElement && ['SCRIPT', 'STYLE'].includes(node.parentElement.tagName)) continue;
      const source = node.nodeValue.trim();
      if (!source || !dictionary[source]) continue;
      node.nodeValue = node.nodeValue.replace(source, dictionary[source]);
    }
    for (const element of root.querySelectorAll('[placeholder], [aria-label], [title]')) {
      for (const attribute of ['placeholder', 'aria-label', 'title']) {
        const source = element.getAttribute(attribute);
        if (source && dictionary[source]) element.setAttribute(attribute, dictionary[source]);
      }
    }
  }

  window.ARXL_I18N = { language, t, localizeDocument };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', () => localizeDocument());
  else localizeDocument();
})();
